<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Arca.UI.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\..\src\Arca.UI\Arca.UI.csproj" />
    <ProjectReference Include="..\Arca.Testing\Arca.Testing.csproj" />
  </ItemGroup>
</Project>
