<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Arca.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Security\CommonPasswords.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arca.Domain\Arca.Domain.csproj" />
  </ItemGroup>
</Project>
