<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Arca.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
    <ProjectReference Include="..\Arca.Application\Arca.Application.csproj" />
  </ItemGroup>
</Project>
