// <auto-generated />
using System;
using Arca.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arca.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(ArcaDbContext))]
    [Migration("20260930193636_HomeCards")]
    partial class HomeCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Arca.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YearId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockerId")
                        .IsUnique()
                        .HasFilter("\"EndedAtUtc\" IS NULL");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("\"EndedAtUtc\" IS NULL");

                    b.HasIndex("YearId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Catalog.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LevelId", "NameKey")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Catalog.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("Levels", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Charges.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Return")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("ReturnStatus");

                    b.Property<string>("ReturnNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReturnedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YearId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("\"Concept\" = 'Deposit' AND \"Status\" <> 'Voided' AND \"ReturnStatus\" <> 'Returned'");

                    b.HasIndex("StudentId", "Status");

                    b.HasIndex("StudentId", "YearId")
                        .IsUnique()
                        .HasFilter("\"Concept\" = 'Fee'");

                    b.HasIndex("YearId", "Status");

                    b.ToTable("Charges", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.ConceptAmounts.ConceptAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YearId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YearId", "Concept")
                        .IsUnique();

                    b.ToTable("ConceptAmounts", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YearId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LevelId");

                    b.HasIndex("YearId");

                    b.HasIndex("StudentId", "YearId")
                        .IsUnique();

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Home.HomeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedKey")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.HasIndex("SeedKey")
                        .IsUnique();

                    b.ToTable("HomeCards", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Home.HomeCardsState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DefaultsCreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HomeCardsState", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Identity.CentreIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Accent")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentreIdentity", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Lockers.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutOfService")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservedForStudentId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetiredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("\"RetiredAtUtc\" IS NULL");

                    b.HasIndex("ZoneId");

                    b.ToTable("Lockers", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.SchoolYears.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcademicYears", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetiredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetirementReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NameKey");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("Arca.Infrastructure.Charges.ChargeEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId", "OccurredAtUtc");

                    b.ToTable("ChargeEvents", (string)null);
                });

            modelBuilder.Entity("Arca.Infrastructure.ConceptAmounts.ConceptAmountEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptAmountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptAmountId", "OccurredAtUtc");

                    b.ToTable("ConceptAmountEvents", (string)null);
                });

            modelBuilder.Entity("Arca.Infrastructure.Inventory.LockerEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockerId", "OccurredAtUtc");

                    b.ToTable("LockerEvents", (string)null);
                });

            modelBuilder.Entity("Arca.Infrastructure.Students.StudentEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "OccurredAtUtc");

                    b.ToTable("StudentEvents", (string)null);
                });

            modelBuilder.Entity("Arca.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("Arca.Domain.Lockers.Locker", null)
                        .WithMany()
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arca.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arca.Domain.SchoolYears.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Domain.Catalog.Group", b =>
                {
                    b.HasOne("Arca.Domain.Catalog.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Domain.Charges.Charge", b =>
                {
                    b.HasOne("Arca.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arca.Domain.SchoolYears.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Domain.ConceptAmounts.ConceptAmount", b =>
                {
                    b.HasOne("Arca.Domain.SchoolYears.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Domain.Enrollments.Enrollment", b =>
                {
                    b.HasOne("Arca.Domain.Catalog.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Arca.Domain.Catalog.Level", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arca.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arca.Domain.SchoolYears.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Domain.Lockers.Locker", b =>
                {
                    b.HasOne("Arca.Domain.Zones.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Infrastructure.Charges.ChargeEventRow", b =>
                {
                    b.HasOne("Arca.Domain.Charges.Charge", null)
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Infrastructure.ConceptAmounts.ConceptAmountEventRow", b =>
                {
                    b.HasOne("Arca.Domain.ConceptAmounts.ConceptAmount", null)
                        .WithMany()
                        .HasForeignKey("ConceptAmountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Infrastructure.Inventory.LockerEventRow", b =>
                {
                    b.HasOne("Arca.Domain.Lockers.Locker", null)
                        .WithMany()
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Arca.Infrastructure.Students.StudentEventRow", b =>
                {
                    b.HasOne("Arca.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
