<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Arca.Desktop</RootNamespace>
    <AssemblyName>Arca</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\Arca.Application\Arca.Application.csproj" />
    <ProjectReference Include="..\Arca.Infrastructure\Arca.Infrastructure.csproj" />
    <ProjectReference Include="..\Arca.UI\Arca.UI.csproj" />
  </ItemGroup>
</Project>
